(()=>{
const DRAFT_KEY="gmm_web_draft_v1",RECORDS_KEY="gmm_web_records_v1";
let records=[],activeId="",selectedId="",ready=false,timer=0;
const zh={auto:"自动保存开启",saved:"草稿已自动保存",newQuote:"新建报价",saveQuote:"保存报价",saveHistory:"保存到历史记录",history:"历史记录",historyTitle:"报价历史记录",historyDesc:"所有报价保存在当前设备，可随时查看、继续编辑或重新导出。",back:"返回当前报价",savedQuotes:"已保存报价",choose:"选择一份报价查看完整明细。",view:"查看",edit:"继续编辑",export:"重新导出 .xlsx",unnamed:"未命名报价",noClient:"未填写客户",savedAt:"保存时间",items:"项目数量",unit:"份",savedToast:"已保存到历史记录",deleted:"历史记录已删除",deleteAsk:"删除这份历史记录？",newAsk:"新建报价会清空当前内容，历史记录不会删除。是否继续？",newDone:"已新建报价",empty:"暂无保存记录",emptyDesc:"完成报价后点击“保存到历史记录”。",detail:"报价详情",amount:"金额 (GHS)",del:"删除",client:"客户名称",project:"项目名称",date:"活动日期",venue:"举办地点",number:"报价编号"};
const en={auto:"Auto-save enabled",saved:"Draft auto-saved",newQuote:"New quotation",saveQuote:"Save quotation",saveHistory:"Save to history",history:"History",historyTitle:"Quotation history",historyDesc:"Quotations are saved on this device and can be viewed, edited or exported anytime.",back:"Back to current quotation",savedQuotes:"Saved quotations",choose:"Select a quotation to view its full details.",view:"View",edit:"Continue editing",export:"Export .xlsx again",unnamed:"Untitled quotation",noClient:"Client not entered",savedAt:"Saved",items:"Items",unit:"quotation(s)",savedToast:"Saved to history",deleted:"History record deleted",deleteAsk:"Delete this quotation record?",newAsk:"Starting a new quotation clears the current content. Saved history remains. Continue?",newDone:"New quotation created",empty:"No saved quotations",emptyDesc:"Complete a quotation and choose “Save to history”.",detail:"Quotation details",amount:"Amount (GHS)",del:"Delete",client:"Client name",project:"Project name",date:"Event date",venue:"Venue",number:"Quotation no."};
const L=k=>(typeof lang!=="undefined"&&lang==="en"?en:zh)[k];
const inputs=()=>[...document.querySelectorAll(".meta input")];
const money=n=>"GH₵"+Number(n||0).toLocaleString("en-GH",{minimumFractionDigits:2,maximumFractionDigits:2});
const totalOf=d=>{let s=(d.items||[]).reduce((a,x)=>a+(+x.price||0)*(+x.qty||0),0);return s*(1-(+d.discount||0)/100)*(1+(+d.tax||0)/100)};
const snapshot=()=>({meta:inputs().map(x=>x.value),items:q.map(x=>({...x})),discount:+$("discount").value||0,tax:+$("tax").value||0,updatedAt:new Date().toISOString()});
function persist(){if(!ready)return;let d=snapshot();localStorage.setItem(DRAFT_KEY,JSON.stringify(d));if(activeId){let i=records.findIndex(x=>x.id===activeId);if(i>-1){records[i]={...records[i],...d};saveRecords()}}let s=$("saveStatus");if(s){s.textContent=L("saved");clearTimeout(s._t);s._t=setTimeout(()=>s.textContent=L("auto"),1000)}}
function schedule(){clearTimeout(timer);timer=setTimeout(persist,180)}
function saveRecords(){localStorage.setItem(RECORDS_KEY,JSON.stringify(records))}
function quoteNo(){return "Q-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+String(records.length+1).padStart(3,"0")}
function apply(d){ready=false;let m=inputs();(d.meta||[]).forEach((v,i)=>{if(m[i])m[i].value=v||""});q=(d.items||[]).map(x=>({...x}));$("discount").value=d.discount||0;$("tax").value=d.tax||0;Q();I();ready=true;schedule()}
function blank(){return{meta:["","",new Date().toISOString().slice(0,10),"","",quoteNo(),"",lang==="en"?"Payment according to contract":"按合同约定支付"],items:[],discount:0,tax:0}}
function showFront(){$("historyView").classList.remove("on");$("admin").classList.remove("on");$("front").classList.remove("off")}
function openHistory(){$("front").classList.add("off");$("admin").classList.remove("on");$("historyView").classList.add("on");renderList();renderDetail()}
function newQuote(){let d=snapshot();if((d.items.length||d.meta[0]||d.meta[1])&&!confirm(L("newAsk")))return;activeId="";selectedId="";apply(blank());showFront();T(L("newDone"))}
function saveQuote(){let d=snapshot(),id=activeId||((window.crypto&&crypto.randomUUID)?crypto.randomUUID():"q-"+Date.now()),i=records.findIndex(x=>x.id===id),r={id,createdAt:i>-1?records[i].createdAt:new Date().toISOString(),...d};if(i>-1)records[i]=r;else records.unshift(r);activeId=id;selectedId=id;saveRecords();persist();renderList();renderDetail();T(L("savedToast"))}
function recordTitle(r){return (r.meta&&r.meta[1])||L("unnamed")}
function fmtDate(v){try{return new Date(v).toLocaleString(lang==="en"?"en-GB":"zh-CN",{hour12:false})}catch{return v||""}}
function renderList(){let box=$("historyList");$("historyCount").textContent=records.length+" "+L("unit");if(!records.length){box.innerHTML='<div class="history-empty"><div><b>'+L("empty")+'</b><p>'+L("emptyDesc")+'</p></div></div>';return}box.innerHTML=records.map(r=>'<button class="record-card '+(r.id===selectedId?'on':'')+'" data-record="'+r.id+'"><strong>'+esc(recordTitle(r))+'</strong><span>'+esc((r.meta&&r.meta[0])||L("noClient"))+'</span><small>'+fmtDate(r.updatedAt)+'</small><b>'+money(totalOf(r))+'</b></button>').join("");box.querySelectorAll("[data-record]").forEach(b=>b.onclick=()=>{selectedId=b.dataset.record;renderList();renderDetail()})}
function esc(s){let e=document.createElement("div");e.textContent=s??"";return e.innerHTML}
function renderDetail(){let box=$("historyDetail"),r=records.find(x=>x.id===selectedId);if(!r){box.innerHTML='<div class="history-empty"><div><b>'+L("choose")+'</b></div></div>';return}let pairs=[[0,"client"],[1,"project"],[2,"date"],[3,"venue"],[5,"number"]];box.innerHTML='<div class="tag">'+L("detail")+'</div><h2>'+esc(recordTitle(r))+'</h2><div class="record-meta">'+pairs.map(([i,k])=>'<div><small>'+L(k)+'</small><b>'+esc((r.meta&&r.meta[i])||"—")+'</b></div>').join("")+'</div><div class="record-actions"><button class="btn primary" id="editRecord">'+L("edit")+'</button><button class="btn" id="exportRecord">'+L("export")+'</button><button class="btn red" id="deleteRecord">'+L("del")+'</button></div><div class="tablebox"><table class="record-table"><thead><tr><th>'+tx("项目名称")+'</th><th>'+tx("数量")+'</th><th>'+L("amount")+'</th></tr></thead><tbody>'+(r.items||[]).map(x=>'<tr><td>'+esc(tx(x.name))+'</td><td>'+x.qty+' '+esc(tx(x.unit))+'</td><td>'+money(x.qty*x.price)+'</td></tr>').join("")+'</tbody></table></div><div class="record-total"><b>'+tx("参考总价")+'</b><strong>'+money(totalOf(r))+'</strong></div>';$("editRecord").onclick=()=>{activeId=r.id;apply(r);showFront()};$("exportRecord").onclick=()=>exportRecord(r);$("deleteRecord").onclick=()=>deleteRecord(r.id)}
function deleteRecord(id){if(!confirm(L("deleteAsk")))return;records=records.filter(x=>x.id!==id);if(activeId===id)activeId="";selectedId=records[0]?.id||"";saveRecords();renderList();renderDetail();T(L("deleted"))}
function exportRecord(r){let current=snapshot(),old=activeId;ready=false;apply(r);exportXlsx();apply(current);activeId=old;ready=true}
function createUI(){let actions=document.querySelector(".top>div:last-child"),status=document.createElement("span");status.id="saveStatus";status.textContent=L("auto");document.querySelector(".brand>div:last-child").appendChild(status);let admin=$("adminOpen");[["newQuoteTop","newQuote","btn"],["saveRecordTop","saveQuote","btn primary"],["historyOpen","history","btn"]].forEach(([id,key,cls])=>{let b=document.createElement("button");b.id=id;b.className=cls;b.textContent=L(key);actions.insertBefore(b,admin)});let x=document.createElement("section");x.id="historyView";x.className="history-view";x.innerHTML='<div class="card history-shell"><div class="history-head"><div><div class="tag">ARCHIVE</div><h2 id="historyTitle"></h2><p id="historyDesc"></p></div><button class="btn primary" id="historyBack"></button></div><div class="history-layout"><div class="history-list"><div class="head"><h2 id="savedQuotes"></h2><small id="historyCount"></small></div><div id="historyList"></div></div><div class="history-detail" id="historyDetail"></div></div></div>';$("admin").before(x);let exportBtn=document.querySelector(".totals .wide");let save=document.createElement("button");save.id="saveRecordMain";save.className="btn primary wide";exportBtn.classList.remove("primary");exportBtn.before(save);$("newQuoteTop").onclick=newQuote;$("saveRecordTop").onclick=saveQuote;$("saveRecordMain").onclick=saveQuote;$("historyOpen").onclick=openHistory;$("historyBack").onclick=showFront;updateLabels()}
function updateLabels(){[["newQuoteTop","newQuote"],["saveRecordTop","saveQuote"],["saveRecordMain","saveHistory"],["historyOpen","history"],["historyTitle","historyTitle"],["historyDesc","historyDesc"],["historyBack","back"],["savedQuotes","savedQuotes"]].forEach(([id,k])=>{let e=$(id);if(e)e.textContent=L(k)});let s=$("saveStatus");if(s)s.textContent=L("auto");renderList();renderDetail()}
function hook(){document.addEventListener("input",e=>{if(e.target.closest(".front"))schedule()});document.addEventListener("change",e=>{if(e.target.closest(".front"))schedule()});document.addEventListener("click",e=>{if(e.target.closest(".front")&&e.target.closest("button"))setTimeout(schedule,0)});let oldAdmin=$("adminOpen").onclick;$("adminOpen").onclick=()=>{$("historyView").classList.remove("on");oldAdmin()};let oldLang=$("langToggle").onclick;$("langToggle").onclick=()=>{oldLang();updateLabels()}}
function init(){createUI();hook();try{records=JSON.parse(localStorage.getItem(RECORDS_KEY)||"[]")||[]}catch{records=[]}let draft=null;try{draft=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null")}catch{}if(draft)apply(draft);selectedId=records[0]?.id||"";ready=true;renderList();renderDetail();schedule()}
init();
})();
