import { useMemo, useState } from "react";
import { MagnifyingGlass, Plus, Minus, Trash, DownloadSimple, Printer, Sparkle, CalendarBlank, MapPin, Check, X } from "@phosphor-icons/react";
const ITEMS=[
["LED001","LED屏幕","室内LED主屏 P2.5","按面积","平方米/天",850],["LED002","LED屏幕","户外LED主屏 P3.9","按面积","平方米/天",1100],["LED003","LED屏幕","LED安装结构","按面积","平方米",180],["STG001","舞台搭建","标准舞台","按面积","平方米/天",220],["STG002","舞台搭建","舞台地毯","按面积","平方米",65],["STG003","舞台搭建","舞台台阶","按数量","组/天",450],["LGT001","灯光系统","LED染色灯","按数量","台/天",180],["LGT002","灯光系统","摇头光束灯","按数量","台/天",450],["LGT003","灯光系统","灯光控制台","按数量","套/天",1500],["AUD001","音响系统","线阵列主扩音响","按数量","套/天",6000],["AUD002","音响系统","无线手持麦克风","按数量","支/天",300],["AUD003","音响系统","数字调音台","按数量","台/天",1800],["VIS001","视觉设计","活动主视觉设计","一次性","项",3500],["VIS002","视觉设计","开场视频制作","一次性","条",6000],["PRT001","广告物料","喷绘背景画面","按面积","平方米",95],["PRT002","广告物料","红地毯","按面积","平方米",55],["PRT003","广告物料","易拉宝","按数量","个",450],["FUR001","桌椅帐篷","宴会椅","按数量","把/天",35],["FUR002","桌椅帐篷","圆桌","按数量","张/天",180],["FUR003","桌椅帐篷","户外帐篷","按面积","平方米/天",250],["CAM001","摄影摄像","活动摄影师","按数量","人/天",1800],["CAM002","摄影摄像","活动摄像师","按数量","人/天",2200],["STA001","人员服务","中英双语主持人","一次性","人/场",5000],["STA002","人员服务","礼仪接待","按数量","人/天",700],["PWR001","电力保障","静音发电机","按数量","台/天",3500],["LOG001","运输人工","设备运输","一次性","趟",2500],["LOG002","运输人工","安装拆卸人工","按数量","人/天",500],["CAT001","餐饮接待","会议茶歇","按人数","人/餐",120],["SEC001","安保许可","现场保安","按数量","人/天",600],["TRN001","翻译同传","中英口译员","按数量","人/天",2500]
].map(([id,category,name,method,unit,price])=>({id,category,name,method,unit,price}));
const money=n=>new Intl.NumberFormat("en-GH",{style:"currency",currency:"GHS",minimumFractionDigits:2}).format(n).replace("GHS","GH₵");
export function App(){
 const [search,setSearch]=useState(""),[category,setCategory]=useState("全部"),[quote,setQuote]=useState([]),[discount,setDiscount]=useState(0),[tax,setTax]=useState(0),[notice,setNotice]=useState(false);
 const categories=["全部",...new Set(ITEMS.map(i=>i.category))], shown=ITEMS.filter(i=>(category==="全部"||i.category===category)&&(`${i.name}${i.id}${i.category}`.toLowerCase().includes(search.toLowerCase())));
 const add=item=>{setQuote(q=>q.some(x=>x.id===item.id)?q.map(x=>x.id===item.id?{...x,qty:x.qty+1}:x):[...q,{...item,qty:1}]);setNotice(true);setTimeout(()=>setNotice(false),1200)};
 const update=(id,qty)=>setQuote(q=>q.map(x=>x.id===id?{...x,qty:Math.max(1,Number(qty)||1)}:x));
 const subtotal=useMemo(()=>quote.reduce((s,x)=>s+x.price*x.qty,0),[quote]),discounted=subtotal*(1-discount/100),total=discounted*(1+tax/100);
 return <div className="app-shell"><header className="topbar"><div className="brand"><div className="mark"><Sparkle weight="fill"/></div><div><b>Moneta</b><span>活动报价</span></div></div><div className="header-actions"><button className="ghost" onClick={()=>window.print()}><Printer/>打印</button><button className="primary" onClick={()=>window.print()}><DownloadSimple/>导出报价单</button></div></header><main>
 <section className="intro"><div><p className="eyebrow">会议 · 活动 · 执行</p><h1>快速生成专业活动报价</h1><p>选择服务项目，输入面积或数量，系统将自动计算参考报价。</p></div><div className="meta-card"><label>项目名称<input defaultValue="Accra 年度合作伙伴会议"/></label><div><label><CalendarBlank/>活动日期<input type="date" defaultValue="2026-08-18"/></label><label><MapPin/>举办地点<input defaultValue="Accra"/></label></div></div></section>
 <section className="workspace"><div className="catalog panel"><div className="panel-head"><div><span className="step">01</span><h2>选择服务项目</h2></div><span>{shown.length} 项可选</span></div><div className="search"><MagnifyingGlass/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索项目名称或编号"/>{search&&<button onClick={()=>setSearch("")}><X/></button>}</div><div className="filters">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="items">{shown.map(item=><article className="item" key={item.id}><div className="item-main"><span className="code">{item.id}</span><div><h3>{item.name}</h3><p>{item.category} · {item.method}</p></div></div><div className="price"><b>{money(item.price)}</b><span>/ {item.unit}</span></div><button aria-label="添加项目" className={quote.some(x=>x.id===item.id)?"add added":"add"} onClick={()=>add(item)}>{quote.some(x=>x.id===item.id)?<Check/>:<Plus/>}</button></article>)}{!shown.length&&<div className="empty">没有找到匹配项目，换个关键词试试。</div>}</div></div>
 <aside className="quote panel"><div className="panel-head"><div><span className="step">02</span><h2>报价明细</h2></div><span>{quote.length} 项</span></div><div className="quote-list">{!quote.length?<div className="empty-quote"><div><Sparkle/></div><h3>从左侧添加报价项目</h3><p>面积与数量默认从 1 开始，随改随算。</p></div>:quote.map(x=><div className="quote-row" key={x.id}><div className="row-title"><div><span>{x.category}</span><h3>{x.name}</h3></div><button aria-label="删除项目" onClick={()=>setQuote(q=>q.filter(i=>i.id!==x.id))}><Trash/></button></div><div className="row-calc"><div className="counter"><button onClick={()=>update(x.id,x.qty-1)}><Minus/></button><input aria-label={x.method==="按面积"?"面积":"数量"} value={x.qty} onChange={e=>update(x.id,e.target.value)}/><button onClick={()=>update(x.id,x.qty+1)}><Plus/></button></div><span>× {money(x.price)}</span><b>{money(x.qty*x.price)}</b></div><div className="unit-note">{x.method==="按面积"?"面积":"数量"} · {x.unit}</div></div>)}</div><div className="adjustments"><label>优惠折扣<div><input type="number" min="0" max="100" value={discount} onChange={e=>setDiscount(+e.target.value)}/><span>%</span></div></label><label>税费<div><input type="number" min="0" value={tax} onChange={e=>setTax(+e.target.value)}/><span>%</span></div></label></div><div className="totals"><p><span>项目小计</span><b>{money(subtotal)}</b></p>{discount>0&&<p><span>优惠后</span><b>{money(discounted)}</b></p>}<div><span>参考总价 <small>GHS</small></span><strong>{money(total)}</strong></div></div><button className="generate" disabled={!quote.length} onClick={()=>window.print()}><DownloadSimple/>生成报价单</button><p className="fineprint">参考价格将根据现场条件、运输距离及活动日期最终确认。</p></aside></section></main>{notice&&<div className="toast"><Check weight="bold"/> 已加入报价明细</div>}</div>
}
